#!/bin/sh
set -e
set -v

export ARCH=arm ARM_ARCH=armv7-a
export HOST="$(printf '%s\n' "$MACHTYPE" | sed "s/-[^-]*/-cross/")"
export TARGET=arm-linux-musleabihf FLOAT=hard FPU=vfpv4

export ROOT="$(pwd)"
export DOWNLOADS="$(pwd)/src"
export TOOLS="$(pwd)/tools"
export BUILD="$(pwd)/build"
mkdir -p "$DOWNLOADS" "$TOOLS" "$BUILD"

export DEVICE=sun8i-h3-orangepi-one DEFCONFIG=sunxi
export BOOTARGS="loglevel=1 cma=64M root=/dev/mmcblk0p1 rootwait"

export UBOOT_DEFCONFIG=orangepi_one UBOOT_IMAGE=u-boot-sunxi-with-spl.bin
export SDCARD=/dev/mmcblk0

export PATH="$PATH:$(pwd)/scripts:$TOOLS/bin"
mktools
mksystem
mkuboot

printf 'o\n n\n p\n 1\n 2048\n \n a\n w\n' | fdisk "$SDCARD"
mkfs.ext4 "${SDCARD}p1"

mkdir -p .mnt
mount "${SDCARD}p1" .mnt
mkdir -p .info

chateau -r .mnt -i .info add "$BUILD/filesystem.tar.xz"
chateau -r .mnt -i .info add "$BUILD/network.tar.xz"
chateau -r .mnt -i .info add "$BUILD/linux"*
chateau -r .mnt -i .info add "$BUILD/musl"*
chateau -r .mnt -i .info add "$BUILD/busybox"*

cp scripts/chateau .mnt/bin/
mv .info .mnt/etc/packages 
umount .mnt && rm -rf .mnt

dd if="$BUILD/u-boot.bin" of="$SDCARD" bs=1024 seek=8
