#!/bin/sh

error(){ printf 'chateau: %s\n' "$1" >&2 && exit 1; }

usage(){
    printf '%s\n' "usage: chateau [OPTIONS] COMMAND [ARGS]"
    printf '%s\n' "Alcalinux package manager"
    printf '%s\n'
    printf '%s\n' "Avaliable commands:"
    printf '%s\n' "make FILE      Make a package from cd"
    printf '%s\n' "add FILE       Install a package"
    printf '%s\n' "remove NAME    Uninstall a package"
    printf '%s\n' "list           List installed packages"
    printf '%s\n' ''
    printf '%s\n' "Avaliable options:"
    printf '%s\n' "-r PATH    Change root (/)"
    printf '%s\n' "-i PATH    Change info (/etc/packages)"
    printf '%s\n' "-p         Preview command"
    exit 1
}

need_root(){
    [ -d "$ROOT" ] || error "Non existent root directory"
    ROOT="$(realpath "$ROOT")"
}

need_info(){
    [ -d "$INFO" ] || error "Non existent info directory"
    INFO="$(realpath "$INFO")"
}

command_make(){
    file="$1"
    
    if [ "$PREVIEW" = y ]; then
        printf '%s %s\n' "# These files will be added to" "$1"
        find *
    else
        tar -cf "$file" * 
    fi
    
    unset file
}

command_add(){
    need_root && need_info
    file="$1"; name="$(basename ${file%.tar*})"; pkginfo="$INFO/$name"
    [ -f "$file" ] || error "File not found"
    
    if [ ! -f "$pkginfo" ]; then
        if [ "$PREVIEW" = y ]; then
            printf '%s %s\n' "# These files will be installed into" "$ROOT"
            pkginfo=/dev/stdout
        fi

        tar -tf "$1" | while read -r file; do
            [ -e "$ROOT/$file" ] || printf '%s\n' "$file"
        done > "$pkginfo"
        
        [ "$PREVIEW" = y ] || tar -xf "$1" -C "$ROOT"
    else
        error 'Package already installed'
    fi

    unset file name pkginfo
}

command_remove(){
    need_root && need_info
    name="$1"; pkginfo="$INFO/$name"
    if [ -f "$pkginfo" ]; then
        if [ "$PREVIEW" = y ]; then
            printf '%s %s\n' "# These files will be uninstalled from" "$ROOT"
            cat "$pkginfo"
        else
            cd "$ROOT"
            xargs rm -rf < "$pkginfo"
            rm -rf "$pkginfo"
        fi
    else
        error 'Package not installed'
    fi

    unset name pkginfo
}

command_list(){
    need_info
    if [ "$PREVIEW" = y ]; then
        printf '%s\n' "# This folder will have it's files listed"
        printf '%s\n' "$INFO"
    else
        cd "$INFO" && find * -maxdepth 0 -type f 2>/dev/null
    fi
}

ROOT=/
INFO=/etc/packages/
PREVIEW=n

while getopts "r:i:p" opt; do
    case "$opt" in
     r) ROOT="$OPTARG" ;; i) INFO="$OPTARG" ;; p) PREVIEW='y' ;;
     *) usage >&2 ;;
    esac
done
shift "$(( OPTIND - 1 ))"

command="$1"; shift
case "$command" in
    make|add|remove)
        [ "$#" -eq 1 ] || usage >&2
        command_$command "$1" ;;
    list)
        [ "$#" -eq 0 ] || usage >&2
        command_$command ;;
    *)
        usage >&2 ;;
esac
unset command
